version: '3'
services:
  nginx:
    build: ./nginx
    env_file:
      - .env
    volumes:
      - ./public_html:/var/www/html
    ports:
      - ${WP_ENV_PORT}:80
    depends_on:
      - php
  php:
    build: ./php
    env_file:
      - .env
    volumes:
      - ./public_html:/var/www/html
      - ./vendor:/var/www/vendor
      - ./config:/var/www/config
      - ./php/logs/xdebug:/tmp/xdebug/
      - ./php/logs/nginx:/var/log/nginx
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
  db:
    image: percona:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - ${WP_ENV_DB_PORT}:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: not-so-secure
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: not-so-secure
volumes:
  db_data: {}